try {
    error("oh no, error")
} catch (e) {
    try {
        error("oh no, error 2")
    } catch (f) {
        print("Errors: " + e + " " + f)
    }
}

println("Here")
error("oh no, error 3")
println("Should not get here")